version: 2
proxy:
  log_level: DEBUG
  provider: configmap
  thanos_url: https://localhost:3000
  loki_url: https://localhost:3000
  prom_label_url: https://localhost:3000
  jwks_cert_url: https://sso.apps.c-gepa-play.gepa.vshnmanaged.net/realms/internal/protocol/openid-connect/certs
  tenant_label: namespace
  admin_group: gepardec-run-admins
  port: 8080
db:
  user: multitenant
  password_path: "."
  host: localhost
  port: 3306
  dbName: blubb
  query: "SELECT * FROM users WHERE username = ?"
dev:
  enabled: true
  ServiceAccountToken: "fake"