log:
  level: DEBUG
  log_tokens: false

tenant_provider: configmap

web:
  proxy_port: 8080
  metrics_port: 8081
  host: localhost
  insecure_skip_verify: true
  trusted_root_ca_path: "./certs/"
  jwks_cert_url: https://sso.play.run.gepardec.com/realms/internal/protocol/openid-connect/certs
  service_account_token: "fake"

admin:
  bypass: true
  group: gepardec-run-admins

dev:
  enabled: false
  username: example


db:
  enabled: false
  user: multitenant
  password_path: "."
  host: localhost
  port: 3306
  dbName: example
  query: "SELECT * FROM users WHERE username = ?"

thanos:
  url: https://localhost:9091
  tenant_label: namespace
  cert: "./certs/thanos/tls.crt"
  key: "./certs/thanos/tls.key"

loki:
  url: https://localhost:3100
  tenant_label: kubernetes_namespace_name
  cert: "./certs/loki/tls.crt"
  key: "./certs/loki/tls.key"
