version: 2
dev:
  enabled: true
  service_account_token: "*****"

proxy:
  log_level: DEBUG
  provider: configmap
  upstream_url: "http://localhost:3000"
  upstream_url_loki: "http://localhost:9095/lol/"
  upstream_bypass_url: "http://localhost:9095"
  jwks_cert_url: "https://sso.apps.c-gepa-play.gepa.vshnmanaged.net/realms/internal/protocol/openid-connect/certs"
  tenant_label: namespace
  admin_group: !Gepaplexx
  port: 8080

db:
  enabled: false
  user: multitenant
  password_path: "/etc/secrets/db_secret"
  host: localhost
  port: 3306
  db_name: "blubb"
  query: "SELECT * FROM users WHERE username = ?"