proxy:
  log_level: INFO
  provider: configmap
  thanos_url: https://localhost:3000
  loki_url: https://localhost:3000
  jwks_cert_url: https://sso.example.com/realms/internal/protocol/openid-connect/certs
  admin_group: gepardec-run-admins
  insecure_skip_verify: false
  log_tokens: false
  use_plugin_token: true
  port: 8080
  host: localhost
  tenant_labels:
    thanos: namespace
    loki: kubernetes_namespace_name
db:
  user: multitenant
  password_path: "."
  host: localhost
  port: 3306
  dbName: example
  query: "SELECT * FROM users WHERE username = ?"
dev:
  enabled: false
  username: example
  service_account_token: "fake"