version: 2
proxy:
  log_level: DEBUG
  provider: configmap
  thanos_url: https://localhost:3000
  loki_url: https://localhost:3000
  jwks_cert_url: https://sso.example.com/realms/internal/protocol/openid-connect/certs
  admin_group: gepardec-run-admins
  port: 8080
  tenant_labels:
    thanos: tenant
    loki: tenant
db:
  user: multitenant
  password_path: "."
  host: localhost
  port: 3306
  dbName: example
  query: "SELECT * FROM users WHERE username = ?"
dev:
  enabled: true
  username: example
  ServiceAccountToken: "fake"